{
 "title": "home",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clickhouse_hostname",
    "query": {
     "query": "label_values({__name__ =~ \"chi_clickhouse_metric_Uptime|chi_clickhouse_metric_fetch_errors\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![111](https://terminus-paas.oss-cn-hangzhou.aliyuncs.com/upload/images/cdbf33b8-8f4c-4b0b-9ac3-bafaae05c0d2.jpeg)"
   }
  },
  { "type": "text", "gridPos": { "h": 4, "w": 21, "x": 3, "y": 0 }, "options": { "content": "# **Welecome to erda-bypass**" } },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Non-Ready Nodes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\"}) by(condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Reason",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "AGENT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fluent-bit Net Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container=\"POD\",pod=~\".*fluent-bit.*\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{pod}} {{interface}}"
    }
   ]
  },
  {
   "title": "Prometheus-Agent Net Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container=\"POD\",pod=~\".*prometheus-operator.*\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{pod}} {{interface}}"
    }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 } },
  { "title": "KAFKA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{})"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{})"
    }
   ]
  },
  { "type": "dashlist", "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 } },
  {
   "title": "Subscribed Consumer Groups",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(kminion_kafka_consumer_group_topic_lag{}) by(group_id,topic_name)"
    }
   ]
  },
  { "title": "Storage-Clickhouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "clickhouse_hostname" },
  {
   "title": "CPU Time total $clickhouse_hostname",
   "type": "bargauge",
   "description": "The time which CPU spent on various types of activity total for the selected period",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(chi_clickhouse_event_NetworkSendElapsedMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Network Send"
    },
    {
     "expr": "increase(chi_clickhouse_event_NetworkReceiveElapsedMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Network Receive"
    },
    {
     "expr": "increase(chi_clickhouse_event_DiskReadElapsedMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Disk Read syscall"
    },
    {
     "expr": "increase(chi_clickhouse_event_DiskWriteElapsedMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Disk Write syscall"
    },
    {
     "expr": "increase(chi_clickhouse_event_RealTimeMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Real Time"
    },
    {
     "expr": "increase(chi_clickhouse_event_UserTimeMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "User Time"
    },
    {
     "expr": "increase(chi_clickhouse_event_SystemTimeMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "System Time"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSIOWaitMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "OS IO Wait"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSCPUWaitMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "OS CPU Wait"
    },
    {
     "expr": "increase(chi_clickhouse_event_OSCPUVirtualTimeMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "OS CPU Virtual"
    },
    {
     "expr": "increase(chi_clickhouse_event_ThrottlerSleepMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Throttler Sleep"
    },
    {
     "expr": "increase(chi_clickhouse_event_DelayedInsertsMilliseconds{hostname=~\"$clickhouse_hostname\"}[1m]) * 1000",
     "legendFormat": "Delayed Insert"
    },
    {
     "expr": "increase(chi_clickhouse_event_ZooKeeperWaitMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Zookeeper Wait"
    },
    {
     "expr": "increase(chi_clickhouse_event_CompileExpressionsMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Compile Expressions"
    },
    {
     "expr": "increase(chi_clickhouse_event_MergesTimeMilliseconds{hostname=~\"$clickhouse_hostname\"}[1m]) * 1000",
     "legendFormat": "Merges"
    },
    {
     "expr": "increase(chi_clickhouse_event_RWLockReadersWaitMilliseconds{hostname=~\"$clickhouse_hostname\"}[1m]) * 1000",
     "legendFormat": "RWLock Reader Wait"
    },
    {
     "expr": "increase(chi_clickhouse_event_RWLockWritersWaitMilliseconds{hostname=~\"$clickhouse_hostname\"}[1m]) * 1000",
     "legendFormat": "RWLock Writer Wait"
    },
    {
     "expr": "increase(chi_clickhouse_event_SelectQueryTimeMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Select Query"
    },
    {
     "expr": "increase(chi_clickhouse_event_InsertQueryTimeMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Insert Query"
    },
    {
     "expr": "increase(chi_clickhouse_event_S3ReadMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "S3 Read"
    },
    {
     "expr": "increase(chi_clickhouse_event_S3WriteMicroseconds{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "S3 Write"
    }
   ]
  },
  {
   "title": "Insert Queries $clickhouse_hostname",
   "type": "timeseries",
   "description": "Number of INSERT queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(chi_clickhouse_event_InsertQuery{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Insert"
    },
    {
     "expr": "irate(chi_clickhouse_event_SelectQuery{hostname=~\"$clickhouse_hostname\"}[1m])",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Disk $clickhouse_hostname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_DiskTotalBytes{hostname=~\"$clickhouse_hostname\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "chi_clickhouse_metric_DiskTotalBytes{hostname=~\"$clickhouse_hostname\"}-chi_clickhouse_metric_DiskFreeBytes{hostname=~\"$clickhouse_hostname\"}",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}