{
 "title": "EndToEnd",
 "tags": [ "Provisioning" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "le",
    "query": {
     "query": "label_values(kminion_end_to_end_roundtrip_latency_seconds_bucket,le)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "sending to receiving le(h)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kminion_end_to_end_roundtrip_latency_seconds_bucket{le=\"$le\"}[1h])",
     "legendFormat": "partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "sending to receiving le(h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kminion_end_to_end_roundtrip_latency_seconds_bucket{le=\"$le\"}[1h])",
     "legendFormat": "partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Produce failed Rate(H)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(kminion_end_to_end_messages_produced_failed_total[1h]) / delta(kminion_end_to_end_messages_produced_total[1h])",
     "legendFormat": "Partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Produce timeout Rate(H)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(kminion_end_to_end_messages_lost_total[1h]) / delta(kminion_end_to_end_messages_produced_total[1h])",
     "legendFormat": "partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Produce timeout Rate(H)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(kminion_end_to_end_messages_lost_total[1h]) / delta(kminion_end_to_end_messages_produced_total[1h])",
     "legendFormat": "partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Produce failed Rate(H)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(kminion_end_to_end_messages_produced_failed_total[1h]) / delta(kminion_end_to_end_messages_produced_total[1h])",
     "legendFormat": "{{partition_id}}"
    }
   ]
  },
  {
   "title": "produce response time(h)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kminion_end_to_end_produce_latency_seconds_bucket{le=\"$le\"}[1h])",
     "legendFormat": "partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "offset response time(h)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kminion_end_to_end_offset_commit_latency_seconds_bucket{le=\"$le\"}[1h])",
     "legendFormat": "{{coordinator_id}}"
    }
   ]
  }
 ]
}