{
 "title": "Consumer Group",
 "description": "Kafka Topic metrics exported by KMinion",
 "tags": [
  "KMinion",
  "Kafka",
  "Provisioning"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_lag{}, topic_name)"
    }
   },
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_lag{topic_name=\"$topic\"}, group_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topic Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Offset Commit Rate",
   "type": "stat",
   "description": "平均每分钟消费量",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sum(rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumerGroup\",topic_name=\"$topic\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Consumergroup => Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})",
     "legendFormat": "{{group_id}} => {{topic_name}}"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{topic_name}}"
    },
    {
     "expr": "avg by (topic_name, group_id) (rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumerGroup\", topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Consuming: {{topic_name}}"
    }
   ]
  }
 ]
}