{
 "title": "Performance",
 "tags": [
  "Kafka",
  "Provisioning"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "request",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_totaltimems, request)"
    }
   },
   {
    "name": "jobs",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$request Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "request" },
  {
   "title": "Producer - RequestQueueTimeMs",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isnt large enough. The request queue size should match the number of connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestqueuetimems{job=~\"$jobs\",request=\"$request\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Producer - LocalTimeMs",
   "type": "timeseries",
   "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_localtimems{job=~\"$jobs\",request=\"$request\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Producer - RemoteTimeMs",
   "type": "timeseries",
   "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_remotetimems{job=~\"$jobs\",request=\"Produce\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Producer - ResponseQueueTimeMs",
   "type": "timeseries",
   "description": "A high value can imply there aren't enough network threads or the network cant dequeue responses quickly enough, causing back pressure in the response queue. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_responsequeuetimems{job=~\"$jobs\",request=\"Produce\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Producer - ResponseSendTimeMs",
   "type": "timeseries",
   "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network cant dequeue responses of the TCP socket as quickly as theyre being created. If the network buffer gets full, Kafka will block. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_responsesendtimems{job=~\"$jobs\",request=\"$request\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  }
 ]
}