{
 "title": "erda-fluent-bit",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tail插件输入流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total{name='tail.0', pod='$pod'}[1m])",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "Tail插件输入流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total{name='tail.0',pod='$pod'}[1m])",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "HTTP插件重试次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_retried_records_total{name=\"http.0\",pod='$pod'}[1m])",
     "legendFormat": "{{pod}} {{name}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod='$pod'}[1m]) * 100) by (pod)",
     "legendFormat": "total-{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{container!=\"POD\",pod='$pod'}[1m]) * 100) by (pod)",
     "legendFormat": "user-{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{container!=\"POD\",pod='$pod'}[1m]) * 100) by (pod)",
     "legendFormat": "sys-{{pod}}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\",pod='$pod'}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{container!=\"POD\",pod='$pod'}[1m])",
     "legendFormat": "{{pod}} {{device}}"
    }
   ]
  },
  {
   "title": "Net Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container=\"POD\",pod='$pod', interface=\"eth0\"}[1m])",
     "legendFormat": "{{pod}} {{interface}}"
    }
   ]
  }
 ]
}