{
 "title": "fluent-bit",
 "tags": [
  "Provisioning",
  "Agent",
  "Agent:Log"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent Bits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{exported_pod=~\".*fluent-bit.*\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "No Ready Pod Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{exported_pod=~\".*fluent-bit.*\"}) by(phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Non-Ready Nodes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\"}) by(condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~'$pod'}[1m]) * 100) by (pod)",
       "legendFormat": "total_{{pod}}"
      },
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{container!=\"POD\",pod=~'$pod'}[1m]) * 100) by (pod)",
       "legendFormat": "user_{{pod}}"
      },
      {
       "expr": "sum(rate(container_cpu_system_seconds_total{container!=\"POD\",pod=~'$pod'}[1m]) * 100) by (pod)",
       "legendFormat": "sys_{{pod}}"
      }
     ]
    },
    {
     "title": "内存使用",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"POD\",pod=~'$pod'}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{container!=\"POD\",pod=~'$pod'}[1m])",
       "legendFormat": "{{pod}} {{device}}"
      }
     ]
    },
    {
     "title": "Net Output",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{container=\"POD\",pod=~'$pod', interface=\"eth0\"}[1m])",
       "legendFormat": "{{pod}} {{interface}}"
      }
     ]
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Input Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{name!=\"erda_log_export\",pod=~'$pod'}[5m])) by (instance,name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{name!=\"erda.1\",pod=~'$pod'}[5m])) by (instance)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{name!=\"erda_log_export\",pod=~'$pod'}[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{name!=\"erda.1\",pod=~'$pod'}[5m])) by (instance, name)",
     "legendFormat": "{{ instance }}/{{name}}"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{name!=\"erda.1\",pod=~'$pod'}[1m])) by (instance, name)",
     "legendFormat": "{{instance}} Retries to {{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{name!=\"erda.1\",pod=~'$pod'}[1m])) by (instance, name)",
     "legendFormat": "{{instance}} Failed Retries to {{ name }}"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{name!=\"erda.1\",pod=~'$pod'}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Filter Drop Records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_filter_drop_records_total{pod=~'$pod'}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}