{
 "title": "Main-Prometheus(Agent)",
 "tags": [ "Provisioning" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "prometheus version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "last_reload_config",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=\"$job\"}[1h]) * 100)"
    }
   ]
  },
  {
   "title": "conn_established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_established_total{job=\"prometheus\"}",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Send Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_metadata_bytes_total{job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "Send Collector duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"$job\",le=\"0.1\"}[5m])",
     "legendFormat": "P{{le}}"
    },
    {
     "expr": "rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"$job\",le=\"0.05\"}[5m])",
     "legendFormat": "P{{le}}"
    }
   ]
  },
  {
   "title": "Scrape Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(prometheus_target_scrape_pool_sync_total{job=\"$job\"}[5m])",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\"}[5m])) by (scrape_job) * 1000",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  }
 ]
}