{
 "title": "streaming-monitoring",
 "tags": [ "Erda" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": "spot-monitor-log,spot-monitor-metrics,spot-monitor-trace,spot-monitor-notify-record,spot-analyzer-error-insight,spot-monitor-browser,spot-monitor-event,spot-monitor-oap-trace,spot-analyzer-tracing,spot-monitor-trace-event,spot-monitor-entity,spot-monitor-alert-record-event,spot-monitor-alert-record"
   },
   {
    "name": "pod",
    "label": "pod name",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "实例CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~'$pod'}[1m]) * 100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Net IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container=\"POD\", pod='$pod', interface=\"eth0\"}[1m])",
     "legendFormat": "transmit:{{pod}}:{{interface}}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{container=\"POD\", pod='$pod', interface=\"eth0\"}[1m])",
     "legendFormat": "receive:{{pod}}:{{interface}}"
    }
   ]
  },
  {
   "title": "实例内存-container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod='$pod', container!='POD'}",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_memory_cache{pod='$pod', container!='POD'}",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "实例内存-go",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{pod='$pod'}",
     "legendFormat": "InUse {{instance}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{pod='$pod'}",
     "legendFormat": "Heap Total{{instance}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{pod='$pod'}",
     "legendFormat": "Heap Idle {{instance}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{pod='$pod'}",
     "legendFormat": "Heap Release {{instance}}"
    }
   ]
  },
  {
   "title": "others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Data Pipeline Receivers处理速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(data_pipeline_receiver_consumed_total[1m])",
     "legendFormat": "{{pipeline}}: {{receiver}}"
    }
   ]
  },
  {
   "title": "Data Pipeline Processors处理速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(data_pipeline_exporter_consumed_total[1m])",
     "legendFormat": "{{pipeline}}: {{exporter}}"
    }
   ]
  },
  {
   "title": "Data Pipeline Processors处理速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(data_pipeline_processor_consumed_total[1m])",
     "legendFormat": "{{pipeline}}: {{processor}}"
    }
   ]
  },
  {
   "title": "Data Pipeline rp队列堆积",
   "type": "timeseries",
   "description": "事件堆积在receiver到processor队列中的比率",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(data_pipeline_channel_rp_size / data_pipeline_channel_rp_cap) * 100",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Data Pipeline pe队列堆积",
   "type": "timeseries",
   "description": "事件堆积在processor到exporter队列中的比率",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(data_pipeline_channel_rp_size / data_pipeline_channel_rp_cap) * 100",
     "legendFormat": "{{pipeline}}"
    }
   ]
  }
 ]
}