{
 "title": "Overview",
 "tags": [
  "Provisioning",
  "clickhouse"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GlobalThreadActive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_GlobalThreadActive{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "LocalThreadActive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "chi_clickhouse_metric_LocalThreadActive{}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_Query{}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(chi_clickhouse_event_InsertedBytes{}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$datasource Disk",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT free_space as free,total_space as total FROM system.disks;"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "second index",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT table,name,type,expr,granularity FROM system.data_skipping_indices"
    }
   ]
  },
  { "title": "$datasource Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "datasource" },
  {
   "title": "mergeing",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select * from system.merges\nwhere 1=1\nand progress < 1"
    }
   ]
  },
  {
   "title": "process history",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT elapsed,client_hostname,concat(toString(read_rows), ' rows / ', formatReadableSize(read_bytes)) as read,concat(toString(written_rows), ' rows / ', formatReadableSize(written_bytes)) as write,formatReadableSize(memory_usage) as memory,query,ProfileEvents\nFROM system.processes\nwhere is_cancelled=0\norder by elapsed desc\n"
    }
   ]
  },
  {
   "title": "Crash log",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT * FROM system.crash_log\nwhere $__timeFilter(event_time)\n ORDER BY event_time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM system.errors\nWHERE value > 0\nAND $__timeFilter(last_error_time)\nORDER BY code ASC\nLIMIT 1"
    }
   ]
  }
 ]
}