{
 "title": "Slow Processing",
 "tags": [
  "datasource:Clickhouse",
  "Performance",
  "Provisioning"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "query": "metric,log,spans" },
   {
    "name": "queryKind",
    "query": "SELECT distinct query_kind\nFROM system.query_log\nWHERE type = 'QueryFinish'\n  AND $__timeFilter(event_time)\n  and indexOf(databases,'monitor') > 0\n  and indexOf(tables,'monitor.metrics_meta') <=0\n  and arrayExists(x -> x like '%$type%', tables) = 1\n"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT query_kind as kind,count(1) as total\nFROM system.query_log\nWHERE type = 'QueryFinish'\n  AND $__timeFilter(event_time)\n  and indexOf(databases,'monitor') > 0\n  and indexOf(tables,'monitor.metrics_meta') <=0\n  and arrayExists(x -> x like '%$type%', tables) = 1\ngroup by query_kind"
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT query_kind as kind,avg(query_duration_ms) as avg_query_duration_ms\nFROM system.query_log\nWHERE type = 'QueryFinish'\n  AND $__timeFilter(event_time)\n  and indexOf(databases,'monitor') > 0\n  and indexOf(tables,'monitor.metrics_meta') <=0\n  and arrayExists(x -> x like '%$type%', tables) = 1\ngroup by query_kind"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "long duration $queryKind",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT max(query_duration_ms)   query_duration_ms,\n       count(1) as count,\n       normalizeQuery(query) AS normalized_query\nFROM system.query_log\nWHERE type = 'QueryFinish'\n  AND query_kind = '${queryKind}'\n  AND $__timeFilter(event_time)\n  and indexOf(databases,'monitor') > 0\n  and indexOf(tables,'monitor.metrics_meta') <=0\n  and arrayExists(x -> x like '%$type%', tables) = 1\ngroup by normalized_query\nORDER BY query_duration_ms DESC\n"
    }
   ]
  },
  {
   "title": "real time $queryKind",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT query_start_time,\n       query_duration_ms,\n       arrayElement(tables,1) as table,\n       query                                                       AS query,\n       concat(toString(read_rows), ' rows / ', formatReadableSize(read_bytes))     AS read,\n       concat(toString(result_rows), ' rows / ', formatReadableSize(result_bytes)) AS result,\n       formatReadableSize(memory_usage)                                            AS \"memory usage\"\nFROM system.query_log\nWHERE type = 'QueryFinish'\n  AND query_kind = '${queryKind}'\n  AND $__timeFilter(event_time)\n  and indexOf(databases,'monitor') > 0\n  and indexOf(tables,'monitor.metrics_meta') <=0\n  and arrayExists(x -> x like '%$type%', tables) = 1\norder by query_duration_ms desc\nLIMIT 2000"
    }
   ]
  }
 ]
}